### ISSUE TITLE
Wrong username or password - Unable to connect to the demo.

### ISSUE THREAD

**Issue by KoxSosen** [ironsmile/httpms-mobile#6]
Hello!

I recently discovered this project, and it seems very nice, and well done. I'm plannning on self hosting an instance, but wanted to give a try to the mobile application before doing so, using the **Demo site**.

Once I open the application, and try to log in to the Demo site, I get a "Wrong username or password" error. I ensured that I'm using the  right credentials ( copied 1:1 from the website ), and still same error.

- Steps to reproduce:
1, Download Euterpe from the GitHub releases to an Android device.
2, Launch the app, and select "Manual Entry".
3, Set ( https://demo.listen-to-euterpe.eu/ ) as the euterpe address.
4, Fill in the right credentials copied from (
https://listen-to-euterpe.eu/demo )

**Comment by KoxSosen** [comment]
![IMG_20211016_090229](https://user-images.githubusercontent.com/67807644/137577428-511e2a8c-297b-4b8f-b8a5-9c272e64a929.jpg)

**Comment by KoxSosen** [comment]
- Update: Scanning the Barcode seems to work, however that might not be relevant to this issue.

**Comment by ironsmile** [comment]
Wow, thank you for the great bug report! You are indeed using the correct address and credentials so this is puzzling. I will look into it.

**Comment by ironsmile** [comment]
I found the problem and it is fixed in v0.8.1. You can find in on the release page on the FDroid repository if you're using it.

It was a bit embarrassing bug, to be honest 😅 When the server address entered had a `/` at the end (e.g. `https://demo.listen-to-euterpe.eu/` instead of `https://demo.listen-to-euterpe.eu`) then it was doing all of its requests to `//v1/...` instead of `/v1/...`. Which not an issue, normally. But for the login endpoint it is since there is a very strict authentication exception for it and it was failing with double slashes at the start.

Anyway, this is now fixed and v0.8.1 would work for all Euterpe servers even if they are too strict. In the next server version this will be fixed on the server side as well so that older mobile app versions would work with newer servers.

**Comment by KoxSosen** [comment]
Hello! I'm glad that you found the bug! Thank you for the fast response, and fix! And, happy birthday to your brother! 🎉
